//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxtrotProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog
    {
        public int CompanyID { get; set; }
        public System.DateTime InterchangeId { get; set; }
        public int ProductID { get; set; }
        public string ProductName1 { get; set; }
        public string ProductName2 { get; set; }
        public string ItemUnit { get; set; }
        public string ProductDesreptionLong { get; set; }
        public string Synonyms { get; set; }
        public string ProductGroup { get; set; }
        public double Weight { get; set; }
        public string MinQuantity { get; set; }
        public double Price { get; set; }
        public double Discount { get; set; }
        public double NetPrice { get; set; }
        public string Pcode { get; set; }
        public int DistCode { get; set; }
        public string column_17 { get; set; }
    }
}
