//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxtrotProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public Nullable<int> Period { get; set; }
        public string Status { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> ContractID { get; set; }
        public string SubscriptionStatus { get; set; }
    }
}
